### PR TITLE
Add missing wandb_publication parameter on finetune-student task.

### LINKED ISSUE #553: CI pollutes W&B
See https://wandb.ai/moz-translations/ru-en, the runs appear to be fresh.

### PR DESCRIPTION
**Pull request by La0**
Closes #553

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
Should we be default this to False instead, or is the risk of pollution better than the risk of not publishing at all? (@eu9ene or @gregtatum - that's probably a question for you.)

**Comment by eu9ene** [comment]
> Should we be default this to False instead, or is the risk of pollution better than the risk of not publishing at all? (@eu9ene or @gregtatum - that's probably a question for you.)

Yes, pollution is less risky than losing data :)

**Comment by eu9ene** [comment]
However, I think we should not publish anything if the env variable is not set. I can imagine us adding more steps that publish to W&B and forgetting to set it.

**Review by eu9ene — CHANGES_REQUESTED** [review]
Let's not publish anything if the variable is not explicitly set. This would minimize encountering this issue when adding more publishing from other steps.

**Comment by La0** [comment]
I disabled the publication by default, and moved the logic to a CLI args, as all other parameters.

**Review by eu9ene — APPROVED** [review]

**Pull request merged**
