### PR TITLE
Disable spot instances for training

### LINKED ISSUE #356: Disable spot instances for training
We should use regular GCP instances for the long training jobs since it increases wait time and uncertainty for a person who run an experiment:
train-backward
train-teacher
train-student

We can enable spot instances again when we setup training continuation on restart: #270

### PR DESCRIPTION
**Pull request by gabrielBusta**
fixes #356

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
Looks good to me! I suggest that you double check that these instances come up correctly on a branch before merging.

**Comment by gabrielBusta** [comment]
@bhearsum I think there might be an issue. I haven't seen the new instances pick up the tasks in the PR and its been about 40 minutes

**Comment by gabrielBusta** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/Sq2XaUq6RxWY8be0VA03jQ

**Comment by bhearsum** [comment]
> https://firefox-ci-tc.services.mozilla.com/tasks/Sq2XaUq6RxWY8be0VA03jQ

I ended up canceling the pending training task in this task group due to https://bugzilla.mozilla.org/show_bug.cgi?id=1875371#c9

**Comment by bhearsum** [comment]
Also a reminder: we need to put together a list of what we need to turn spot instances back on, perhaps as a new issue in this repo?

**Comment by gabrielBusta** [comment]
Looks like the non-spot instances are picking up tasks now!

https://firefox-ci-tc.services.mozilla.com/tasks/GpiEGvO0TcadEyvC_kn5Fg

**Pull request merged**
