### PR TITLE
Create Dockerfile - use firefox-translations-training in docker

### PR DESCRIPTION
**Pull request by AmitMY**

### CODE REVIEW

**Comment by eu9ene** [comment]
@AmitMY this is definitely useful for people to start using the pipeline and spend less time on setting up the machine. We should think about usage use cases though.

Why we compile marian and other tools as a part of the graph and not in the image is because in cluster mode it's important to compile on a target machine where the job will be executed and it's usually not the head machine. Also, a user should be able to mount volumes and edit the code outside of the container in the notebook for example. All compiled tools are stored inside the repo now and snakemake stores temporary files in `.snakemake` also inside the repo. 

I imagine the following scenario for the local docker use case:
1. `git clone the repo`
2. `make get-modules`
3. build docker image (or `make build-docker`) - add only files that are needed, install dependencies, conda and snakemake inside the image
4. `docker run -it ... bash` (or `make docker`) - mounts the repo we cloned to the container, mounts the data directory and runs the container
5. configure makefile and profile to point to conda inside docker container
6. `make dry-run` (I think it installs conda environments inside .snakemake directory inside the repo on this step)
7. `make test` - it complies marian and other dependencies in the mounted directory inside the repo and executes other steps
8. it is possible to docker stop the container - all the edited code, envs, compiled tools and data will be saved in the mounted volumes
9. then it's possible to start the container again and do `make run` right away, nothing needs to be installed at this point

Please take a look at the latest changes in the main branch, conda directory from makefile can be different from data directory in a profile. Maybe there should be a separated profile for local docker use case.

**Comment by AmitMY** [comment]
I agree with your use case - however, please note that currently, trying to run bergamot from `master`, fails.

At the very minimum, I need to understand how to set up a working environment - and that's why I use docker, though I haven't figured out yet what is making things fail. Do you have any idea?

If you run `nvidia-docker build . -t bergamot`, you will see the error. 

image

**Comment by AmitMY** [comment]
Full error, and additional logs:

```bash
make test
```
```
Error in rule marian:
    jobid: 3
    output: /firefox-translations-training/3rd_party/browsermt-marian-dev/build/marian, /firefox-translations-training/3rd_party/browsermt-marian-dev/build/marian-decoder, /firefox-translations-training/3rd_party/browsermt-marian-dev/build/marian-scorer, /firefox-translations-training/3rd_party/browsermt-marian-dev/build/marian-conv, /firefox-translations-training/3rd_party/browsermt-marian-dev/build/spm_train, /firefox-translations-training/3rd_party/browsermt-marian-dev/build/spm_encode, /firefox-translations-training/3rd_party/browsermt-marian-dev/build/spm_export_vocab
    log: /data/logs/ru-en/test/compile-browsermt-marian-dev.log (check log file(s) for error message)
    conda-env: /firefox-translations-training/.snakemake/conda/3cc0ff2979b25f47047895f30c18abba
    shell:
        bash pipeline/setup/compile-marian.sh /firefox-translations-training/3rd_party/browsermt-marian-dev/build 16  >> /data/logs/ru-en/test/compile-browsermt-marian-dev.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Fri Jul 15 14:59:27 2022]
Error in rule marian:
    jobid: 5
    output: /firefox-translations-training/3rd_party/marian-dev/build/marian, /firefox-translations-training/3rd_party/marian-dev/build/marian-decoder, /firefox-translations-training/3rd_party/marian-dev/build/marian-scorer, /firefox-translations-training/3rd_party/marian-dev/build/marian-conv, /firefox-translations-training/3rd_party/marian-dev/build/spm_train, /firefox-translations-training/3rd_party/marian-dev/build/spm_encode, /firefox-translations-training/3rd_party/marian-dev/build/spm_export_vocab
    log: /data/logs/ru-en/test/compile-marian-dev.log (check log file(s) for error message)
    conda-env: /firefox-translations-training/.snakemake/conda/3cc0ff2979b25f47047895f30c18abba
    shell:
        bash pipeline/setup/compile-marian.sh /firefox-translations-training/3rd_party/marian-dev/build 16  >> /data/logs/ru-en/test/compile-marian-dev.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

```
```bash
cat /data/logs/ru-en/test/compile-browsermt-marian-dev.log
```
```
...
[ 62%] Built target libyaml-cpp
make[3]: Leaving directory '/firefox-translations-training/3rd_party/browsermt-marian-dev/build'
[ 62%] Built target fbgemm_generic
[ 63%] Linking CXX static library libsentencepiece.a
make[3]: Leaving directory '/firefox-translations-training/3rd_party/browsermt-marian-dev/build'
[ 63%] Built target sentencepiece-static
make[3]: Leaving directory '/firefox-translations-training/3rd_party/browsermt-marian-dev/build'
[ 63%] Built target SQLiteCpp
make[3]: Leaving directory '/firefox-translations-training/3rd_party/browsermt-marian-dev/build'
[ 63%] Built target fbgemm_avx2
make[2]: Leaving directory '/firefox-translations-training/3rd_party/browsermt-marian-dev/build'
Makefile:155: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/firefox-translations-training/3rd_party/browsermt-marian-dev/build'
```
```bash
cat /data/logs/ru-en/test/compile-marian-dev.log
```
[ 66%] Built target spm_normalize
make[3]: Leaving directory '/firefox-translations-training/3rd_party/marian-dev/build'
make[3]: Leaving directory '/firefox-translations-training/3rd_party/marian-dev/build'
[ 66%] Built target spm_decode
[ 66%] Built target spm_train
[ 66%] Linking CXX executable ../../../../spm_encode
make[3]: Leaving directory '/firefox-translations-training/3rd_party/marian-dev/build'
[ 66%] Built target spm_encode
make[2]: Leaving directory '/firefox-translations-training/3rd_party/marian-dev/build'
Makefile:155: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/firefox-translations-training/3rd_party/marian-dev/build'

**Comment by AmitMY** [comment]
Those errors are solved with:
```Dockerfile
# Marian/NCCL is expecting nvcc in specific location
RUN mkdir /usr/local/cuda/bin/ && ln -s /usr/bin/nvcc /usr/local/cuda/bin/nvcc
# NCCL: unsupported GNU version! gcc versions later than 6 are not supported!
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
# Downloads and compiles additional packages
RUN make test; make test; exit 0
```

New errors are https://github.com/marian-nmt/marian/issues/392

**Comment by AmitMY** [comment]
I have made great progress on this, the `make test` script is finally running.
I will make sure it finishes successfully, and if so, make a new pull request alongside instructions

**Pull request closed without merging**
