### PR TITLE
Use spot instances for PRs (fixes #419)

### LINKED ISSUE #419: use smaller instances for PRs
I just noticed that we run training on 1tb, 4 GPU, non-spot instances for PRs. We should probably switch to much smaller spot instances for them. (Having 4 GPUs might be OK still to speed things up, but I don't see any reason we should use large disks or on-demand instances.)

### PR DESCRIPTION
**Pull request by bhearsum**

### CODE REVIEW

**Comment by bhearsum** [comment]
The `taskgraph-diff` task shows no differences for push graphs. Here's what I found locally for a PR graph:
```
@@ -7642,7 +7642,7 @@
       label: train-backwards-ru-en
       os: linux
       worker-implementation: generic-worker
-    workerType: b-linux-v100-gpu-4-300gb-standard
+    workerType: b-linux-v100-gpu-4-300gb
 train-student-ru-en:
   attributes:
     always_target: false
@@ -7764,7 +7764,7 @@
       label: train-student-ru-en
       os: linux
       worker-implementation: generic-worker
-    workerType: b-linux-v100-gpu-4-1tb-standard
+    workerType: b-linux-v100-gpu-4-1tb
 train-teacher-ru-en-1/1:
   attributes:
     always_target: false
@@ -7894,7 +7894,7 @@
       label: train-teacher-ru-en-1/1
       os: linux
       worker-implementation: generic-worker
-    workerType: b-linux-v100-gpu-4-1tb-standard
+    workerType: b-linux-v100-gpu-4-1tb
 train-vocab-ru-en:
   attributes:
     always_target: false
```

(which is exactly what we want)

**Review by gbrownmozilla — CHANGES_REQUESTED** [review]
#419 says "I don't see any reason we should use large disks" but this keeps the same disk size. Can you comment on that?

**Comment by bhearsum** [comment]
> #419 says "I don't see any reason we should use large disks" but this keeps the same disk size. Can you comment on that?

Thanks for catching that; I'll deal with that here as well.

**Comment by bhearsum** [comment]
New diff is:
```
@@ -7642,7 +7642,7 @@
       label: train-backwards-ru-en
       os: linux
       worker-implementation: generic-worker
-    workerType: b-linux-v100-gpu-4-300gb-standard
+    workerType: b-linux-v100-gpu-4
 train-student-ru-en:
   attributes:
     always_target: false
@@ -7764,7 +7764,7 @@
       label: train-student-ru-en
       os: linux
       worker-implementation: generic-worker
-    workerType: b-linux-v100-gpu-4-1tb-standard
+    workerType: b-linux-v100-gpu-4
 train-teacher-ru-en-1/1:
   attributes:
     always_target: false
@@ -7894,7 +7894,7 @@
       label: train-teacher-ru-en-1/1
       os: linux
       worker-implementation: generic-worker
-    workerType: b-linux-v100-gpu-4-1tb-standard
+    workerType: b-linux-v100-gpu-4
 train-vocab-ru-en:
   attributes:
     always_target: false
```

We should avoid landing this until we're able to run the pipeline again to ensure that the new worker type is OK disk space-wise.

**Review by gbrownmozilla — APPROVED** [review]

**Comment by bhearsum** [comment]
For posterity, the quantize failure is #281

**Pull request merged**
