### PR TITLE
Upgrade Taskgraph and cleanup firefox-translations-training

### PR DESCRIPTION
**Pull request by gabrielBusta**
I updated `taskgraph` to get rid of the in-tree copies of the core `docker_image` and `fetch` transforms. I also set a working default for `task-expires-after` so we only need to specify it when it is not `90 days`.

### CODE REVIEW

**Comment by gabrielBusta** [comment]
Blah it just occurred to me that this is gonna invalidate a lot of cached tasks.

**Comment by eu9ene** [comment]
> Blah it just occurred to me that this is gonna invalidate a lot of cached tasks.

We change the code so often that the caches don't survive between the experiments. I usually stick with one branch without merging from main to complete the experiment and reuse caches.

**Review by eu9ene — APPROVED** [review]

**Review by bhearsum — APPROVED** [review]
Thanks! It looks like this produces identical task graphs.

**Comment by gabrielBusta** [comment]
mm `(core dumped) "${BMT_MARIAN}"/marian-decoder`

**Comment by bhearsum** [comment]
> mm `(core dumped) "${BMT_MARIAN}"/marian-decoder`

That looks like https://github.com/mozilla/firefox-translations-training/issues/281

**Pull request merged**
