### PR TITLE
Bump taskgraph version to 7.4.0.

### LINKED ISSUE #487: Train action is stuck when `start-stage` is being used
I’m trying to run training with `start-stage` and my actions hang and then get killed on timeout: 

https://firefox-ci-tc.services.mozilla.com/tasks/f1vP7g6IRIuFswKEZdd05g 
https://firefox-ci-tc.services.mozilla.com/tasks/VyRu3YyTSxGtJxZ3RFaeIA/runs/0 

@bhearsum suggested that it's probably taking a tremendous amount of time to walk through all of the upstream tasks. We can try bumping [the timeout](https://github.com/mozilla/firefox-translations-training/blob/main/.taskcluster.yml#L230) and adding some [logging on either side of get_ancestors](https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/translations_taskgraph/actions/train.py#L365) as a quick test of that.

### PR DESCRIPTION
**Pull request by bhearsum**
This picks up an optimization that should fix #487.

### CODE REVIEW

**Comment by bhearsum** [comment]
Did a quick sanity check by [firing a previously uncompletable training config](https://firefox-ci-tc.services.mozilla.com/tasks/ZF4uhChuSUycnyNZHackBQ), which successfully completed.

**Review by hneiva — CHANGES_REQUESTED** [review]
You should update .tc.yml decision image to use `mozillareleases/taskgraph:decision-v7.4.0@sha256:eb13ec9b67c93c8394856813bbe69bb876888a5015938d8d811ef3609c00fe21` (from [dockerhub](https://hub.docker.com/layers/mozillareleases/taskgraph/decision-v7.4.0/images/sha256-eb13ec9b67c93c8394856813bbe69bb876888a5015938d8d811ef3609c00fe21?context=explore))

That would allow you to remove reqs `taskcluster/requirements.{in,txt}`

Also remove `${normProjectUpper}_PIP_REQUIREMENTS` (installs said reqs) from .tc.yml and replace `    ~/.local/bin/taskgraph` with just `taskgraph` (since it's available in the PATH)

**Comment by bhearsum** [comment]
> You should update .tc.yml decision image to use `mozillareleases/taskgraph:decision-v7.4.0@sha256:eb13ec9b67c93c8394856813bbe69bb876888a5015938d8d811ef3609c00fe21` (from [dockerhub](https://hub.docker.com/layers/mozillareleases/taskgraph/decision-v7.4.0/images/sha256-eb13ec9b67c93c8394856813bbe69bb876888a5015938d8d811ef3609c00fe21?context=explore))
> 
> That would allow you to remove reqs `taskcluster/requirements.{in,txt}`
> 
> Also remove `${normProjectUpper}_PIP_REQUIREMENTS` (installs said reqs) from .tc.yml and replace ` ~/.local/bin/taskgraph` with just `taskgraph` (since it's available in the PATH)

Done - thank you for the primer on this!

**Comment by bhearsum** [comment]
Note: requirements files are being kept because we have tests that are intended to be run locally and in CI that need to have taskgraph installed.

**Review by hneiva — APPROVED** [review]
LGTM

**Pull request merged**
