### PR TITLE
fix: adjust dependencies, fetches, and cache digests when using the `use` training contiunation mode

### PR DESCRIPTION
**Pull request by bhearsum**
Dependencies and fetches are unused, so they should be removed.

Cache digests should _only_ be influenced by the pretrained teacher parameters (file resources and other parameters are unused - so they do not influence the outcome of the task).

This largely addresses #395 - I've done a number of tests:
- Create new training that re-uses a backwards model from elsewhere; run it up to train-teacher - https://firefox-ci-tc.services.mozilla.com/tasks/groups/H6Z4Icc3Sz2kZLJZBx1qOw
- Modify something that affects mono and corpus cleaning & run training again up to train-teacher - https://firefox-ci-tc.services.mozilla.com/tasks/groups/QEvzJrasTUuj9_WK4dycpA
  - This reruns ~everything _except_ train-backwards
- Modify something that along affects corpus cleaning & un training again up to train-teacher - https://firefox-ci-tc.services.mozilla.com/tasks/groups/Ddfe_YYaTHqRnyjaHVfRFA
  - This reruns corpus chain + train-teacher, but _not_ the mono chain nor train-backwards
- Modify something that only affects mono & run training again up to train-teacher - https://firefox-ci-tc.services.mozilla.com/tasks/groups/ED3iVqD3S_apaesgpiNVQA
  - This reruns the mono chain + train-teacher but still not train-backwards

I've also started testing happens if certain parameters change. For example [this group](https://firefox-ci-tc.services.mozilla.com/tasks/groups/B4FAJPEeQEuqYHDtU5n-Qw) runs with the same parameters, except the `valid-freq` for both `train-backwards` and `train-teacher` have been tweaked to verify that parameter changes don't cause `train-backwards`. Unfortunately, `train-backwards` still ran...so there's still a theoretical issue somewhere.

In any case - I think this patch covers all of the cases we will realistically hit. I plan to try to get to the bottom of the other case in a follow-up.

### CODE REVIEW

**Comment by bhearsum** [comment]
> I've also started testing happens if certain parameters change. For example [this group](https://firefox-ci-tc.services.mozilla.com/tasks/groups/B4FAJPEeQEuqYHDtU5n-Qw) runs with the same parameters, except the valid-freq for both train-backwards and train-teacher have been tweaked to verify that parameter changes don't cause train-backwards. Unfortunately, train-backwards still ran...so there's still a theoretical issue somewhere.

I got the bottom of this. It happens because [the command ends up as part of the digest data](https://github.com/mozilla/firefox-translations-training/blob/d14881ea710a114cbbd85c98db08a12102e328e6/taskcluster/translations_taskgraph/transforms/cached_tasks.py#L75), and my test was changing one of the parameters that influences the command. This wasn't the most realistic test anyways, so I think this actually ignorable...

I ended up doing a different test to verify that the cache digest is unchanged. [This task group](https://firefox-ci-tc.services.mozilla.com/tasks/groups/MQy9GOCeR1eKGJSVPGP_kA) was created with exactly the same parameters as the first test from my earlier comment, but I modified `train.sh` to bust the cache for anything that depends on it. As expected, `train-backwards` did not have to rerun - it only ran `train-teacher`.

**Review by eu9ene — APPROVED** [review]
This should work but it adds complexity to graph definition. An alternative would be to introduce a new kind to download models and adjusting dependencies in downstream tasks. Then we would have the cleaner kinds that almost don't change, only the dependencies would be adjusted. The final graph would show a different task. The downside is that the backward model is used in multiple places so we would need to modify multiple other kinds + the ones downstream from teachers which is maybe even more complex in the end.

**Comment by eu9ene** [comment]
If we come up with an elegant solution for https://github.com/mozilla/firefox-translations-training/issues/417 it should help addressing the complexity.

**Comment by eu9ene** [comment]
@bhearsum let's merge this. I need this fix to iterate faster. If something comes up let's iterate in a follow-up PR

**Pull request merged**
