### PR TITLE
Kick off training from the command line

### PR DESCRIPTION
**Pull request by gregtatum**
Example run:

```
➤ task train -- --config configs/spring-2024/cs-en-spring-2024.yml --branch main
task: [train] poetry run python -W ignore utils/train_cli.py --config configs/spring-2024/cs-en-spring-2024.yml --branch main
Using --branch: main
Branch 'main' is up to date with origin.
Looking up "mozilla/firefox-translations-training"
Finding the "Decision Task (push)"

Using config: configs/spring-2024/cs-en-spring-2024.yml

       experiment.name: spring-2024
        experiment.src: cs
        experiment.trg: en
          target-stage: all
    previous_group_ids: ['ThgMJX-PR4Kao_qkk4Aszw']
       train-backwards: {'urls': ['https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/A_omF_rtRWatl_qbfvhmPg/artifacts/public/build'], 'mode': 'use', 'type': 'default'}

Start training? [Y,n]
y
Train action triggered: https://firefox-ci-tc.services.mozilla.com/tasks/Aelin5zbTE2JrVVhnYw5SQ
```

It will also prompt you to login by running an `eval` command which exports the taskcluster credentials.

I had assumed there was an issue associated with this, but I don't see one.

### CODE REVIEW

**Comment by gregtatum** [comment]
Ah, I should add some docs. I forgot.

**Comment by gregtatum** [comment]
Ok, I updated the docs as well.

**Review by bhearsum — APPROVED** [review]
This looks great!

**Comment by gregtatum** [comment]
I just added a fix for #840 as well.

**Pull request merged**
