### PR TITLE
Sync main with release

### PR DESCRIPTION
**Pull request by eu9ene**

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
GitHub makes it difficult to review this well. It looks like this is just a roll up of a bunch of patches though, so I presume it's fine. This is mostly a rubberstamp.

**Review by gabrielBusta — APPROVED** [review]
Looks good to me.

**Comment by gabrielBusta** [comment]
Ah there's some conflicts now...

**Comment by eu9ene** [comment]
Closing in favour of #701 where the conflicts are resolved

**Pull request closed without merging**
